name: Tests

on:
  push:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "**.rs"
    branches:
      - "master"
  pull_request:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "**.rs"
    branches:
      - "master"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo test --verbose
